### ISSUE TITLE
Differences Between Moqups and Staging site

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#115]
# Problem

There are a number of subtleties that have changed from the version in the Moqups. (e.g. Importantly there are saltwater fish instead of freshwater.)

# Proposed Solution

Update Icons: Icons should be white and transparent as per mockup:
<img width="142" alt="screen shot 2018-04-03 at 8 45 50 pm" src="https://user-images.githubusercontent.com/2319504/38269219-394611e6-3780-11e8-9232-8f9589a5deba.png">

Update BIMS Data Module Icons: 
<img width="677" alt="screen shot 2018-04-03 at 8 50 36 pm" src="https://user-images.githubusercontent.com/2319504/38269404-b25de8a6-3780-11e8-8922-03ab4d3c5084.png">

Update background images (we cannot use sea images): 
<img width="1104" alt="screen shot 2018-04-03 at 8 52 39 pm" src="https://user-images.githubusercontent.com/2319504/38269501-f9dff4bc-3780-11e8-95bf-e6fc9e4d84e0.png">

Use footer colours: 
<img width="1100" alt="screen shot 2018-04-03 at 8 53 07 pm" src="https://user-images.githubusercontent.com/2319504/38269524-105dc2be-3781-11e8-8156-df486a98eaa8.png">

Update fonts: 

<img width="744" alt="screen shot 2018-04-03 at 8 53 55 pm" src="https://user-images.githubusercontent.com/2319504/38269577-3cf97d7c-3781-11e8-8272-ca373306312a.png">
should be
<img width="645" alt="screen shot 2018-04-03 at 8 54 00 pm" src="https://user-images.githubusercontent.com/2319504/38269600-4559d818-3781-11e8-9f07-ef73fcc1cc79.png">

**Comment by cchristelis** [comment]
You can ask @carina1000 for any assets you are missing.

**Comment by carina1000** [comment]
Hi guys - I have added all the icons and images in the drive folder: https://drive.google.com/drive/folders/163GKM9P5HwYN-EnGYmAbm8y-tnW-26Gs?usp=sharing 

Please don't hesitate to involve me in this process! If you want to look at the mock-ups again you can find them here: https://app.moqups.com/tim@kartoza.com/0RWHHxCONd/edit/page/a6a99b8ee

**Comment by ann26** [comment]
Hi @carina1000 can you give me permissions to access the moqups please?

**Comment by carina1000** [comment]
Hey @ann26  - @timlinux needs to give you access to the Kartoza Moqups account! Tim, could you please do that.

**Comment by dimasciput** [comment]
Hi @carina1000 , can you check the staging site here : http://staging.healthyrivers.kartoza.com, we updated the layouts.
