### ISSUE TITLE
Catchment area

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#138]
# Actor

Conservation Planner

# Description

A conservation planner wishes to look at the broad stroke data in a Catchment area.

# Postconditions

The data is filtered according to a catchment area.

# Normal Course of Events

1. The user logs onto the site.
2. The user filters the data by a selected catchment area.
3. The user views this data on the map.

# Alternative Courses

1. The user draws a report based on a catchment area.

# Exceptions
None

# Business Rules

# Assumptions

# Notes and Issues

**Comment by gubuntu** [comment]
LEDET has basically the same use case (expressed across various tickets) so we should share the effort here

**Comment by ann26** [comment]
# Proposed Solution
1. Add new model, catchment area (fields: name and geometry location)

2. Add filters on search
- Add search filter by catchment area: filtering search objects only the ones that is located within the catchment area. Then the filtered objects will be shown on the map.

3. Add catchment area panel
- When user click on this panel, user may search catchment area name and then the user may click on one of the search result to view all objects within catchment area.
- User may also click on the map directly to specific catchment area where user already knew and the objects within that catchment area will be shown on the map.

**Comment by cchristelis** [comment]
@ann26, just check in with @timlinux whether we couldn't already use the same catchment area data as we are using for clustering...

**Comment by meomancer** [comment]
hi @cchristelis @timlinux 
clustering just using administrative boundary, not using catchment area
and also when in taxon mode, clustering is using overlapped point-to-point  method, like healthsites

**Comment by cchristelis** [comment]
@meomancer, I like the idea of drilling into the geocontext data, but yeah, it would be difficult to manage that UX of clicking on the map. Adding a tool like we have with FORD 2 might work. Let's chat through it tomorrow. 

What about querying the geocontext data and doing a catagory selection and then after that a value selection?

**Comment by meomancer** [comment]
hi @cchristelis 
as per i analyze this ticket deeply, i found that the catchment area is basically the administrative boundary on bims. I though it is really catchment area from geocontext.

So we could do this ticket

**Comment by Vries14** [comment]
Administrative area added
