### ISSUE TITLE
Water Affairs - Context layers

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#139]
# Actor

Water Affairs User

# Description

The water affairs user would like to view the data on a specific river. This user is especially interested in the FEPA 2011 context data.

# Preconditions

The FEPA 2011 data has been loaded on the system and is available as context layers.

# Postconditions

The biodiversity layer is visible ontop of various context layers.

# Normal Course of Events

1. The user selects certain layers as context layers 
2. The user filters biodiversity data by a sepcific river. 
3. The user browses the data on the map.
4. The user looks at summary data on the side panel.
5. The user looks at detail data on the dashborad.

# Exceptions
# Business Rules
# Assumptions
# Notes and Issues

**Comment by NyakudyaA** [comment]
@myarjunar the NFEPA layers are available from http://maps.kartoza.com/web/?map=/web/kartoza/kartoza.qgs as well as Lbims GIS.

**Comment by myarjunar** [comment]
@NyakudyaA I can't access that url, is that the correct url ?

**Comment by meomancer** [comment]
hi @NyakudyaA 
is there any way to get geojson/polygon from the layer?
we need polygon for filtering the biodiversity

**Comment by myarjunar** [comment]
@cchristelis it seems like we need to discuss about the efficient solution to filter biodiversity data by context layers. We thought that it will be a huge query to execute. We need to provide some kind of limitations to the query (zoom extent etc). What kind of limitation that is allowed for this filter?

**Comment by gubuntu** [comment]
you can get any vector data as GeoJSON via a WFS request, which you can also filter. 

I would show and example on on lbims geoserver but it's down atm.

**Comment by NyakudyaA** [comment]
@myarjunar try to get the layers from http://maps.kartoza.com/geoserver/
Example layer: http://maps.kartoza.com/geoserver/kartoza/wms?service=WMS&version=1.1.0&request=GetMap&layers=kartoza:rivers-nfepa&styles=&bbox=1774016.875,-4141456.25,3790971.5,-2255659.25&width=768&height=718&srs=EPSG:3857&format=application/json;type=geojson

**Comment by cchristelis** [comment]
@myarjunar, the healthyrivers search panel will have certain spatial queries see: https://app.moqups.com/tim@kartoza.com/0RWHHxCONd/edit/page/a022ae652, these include certain spatial queries. Let's start with just including catchment areas...

**Comment by cchristelis** [comment]
https://app.moqups.com/tim@kartoza.com/0RWHHxCONd/view <-- @myarjunar, this project is public, but you should anyway be able to access it from you kartoza account.
