### ISSUE TITLE
KBIMS - Healthyrivers

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#141]
# Problem

There has been some development on KBIMS that needs to be integrated with healthyrivers.

# Proposed Solution

Please update the healthyrivers project to include all these changes.

**Comment by cchristelis** [comment]
@dimasciput, has this been deployed?

**Comment by dimasciput** [comment]
@cchristelis not yet, like I said this is long process because of how healthyrivers is very left behind. I need one day, I will try to deploy this afternoon.
