### ISSUE TITLE
Clusters

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#145]
# Error
When clicking on a cluster you get navigated  to a different area that's close to the sites.
# Expected behaviour
When a cluster gets clicked, navigation should be to the centre of the cluster.

I clicked on the yellow cluster below:
![cluster](https://user-images.githubusercontent.com/42169058/44148857-3639db08-a09a-11e8-87db-602cc0ffb1ca.png)

The following was my result.
![redirect.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46fa919e2a9086aa9babf301b44fff9e2c4533317346f62a25d6b629e91023520e564cfe41585e16fbf0d82ff4e52e6c981e5ab38532022d8c6853beb2901eb70bbb25884b86b2bd824bc9e83523f5c6.png)

**Comment by dimasciput** [comment]
This has been fixed in latest django-bims, please try again.

**Comment by dimasciput** [comment]
@Vries14

**Comment by Vries14** [comment]
This error is no longer present.
