### ISSUE TITLE
Unusable arrow keys

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#147]
# Bug report

1.Go to locate options.
2.Search using "locate by coordinate".
3. In the longitude use the up and down arrow keys to add a value.

# Error

The last decimal is being changed when using the arrow keys. That would take a long time to reach a number like 33.9321

# Expected behaviour

Values should be changing from another point, maybe after the decimal.

**Comment by dimasciput** [comment]
I don't think this is a bug, more like enhancement.
