### ISSUE TITLE
Popup

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#148]
# Bug report

1. Click on the search icon and do a search on "Cyprinus carpio"
2.Click on sites.
3.Select "baviaans".
4.Double click on the pink navigation icon.

# Error

A pop-up with information  is showing on screen above the icon.

# Expected behaviour

All information are to be on the right hand side

**Comment by dimasciput** [comment]
@Vries14 This has been fixed in latest django-bims, please try again.

**Comment by Vries14** [comment]
This issue is no longer present.
