### ISSUE TITLE
Fish Side Panel

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#150]
# Problem

There has been some work done on the side-panel UI, which has not been implemented. Since these changes have been developed with the client, it is high value to have the side panel match the mockups.

# Proposed Solution

Bring the side-panel in line with the mockup at: 
https://app.moqups.com/tim@kartoza.com/0RWHHxCONd/edit/page/aeb832dac

**Comment by cchristelis** [comment]
[Uploading Screen Shot 2018-08-16 at 9.25.41 AM.png...]

**Comment by ann26** [comment]
hi @cchristelis 
for this one:
![screenshot from 2018-08-16 15-00-39](https://user-images.githubusercontent.com/26101337/44196112-3fdcbd80-a165-11e8-974b-c741355f62b9.png)
From which data this diagram is based on?

Also, could you (or maybe @carina1000 ) point me to where the icon is?

**Comment by timlinux** [comment]
@ann26 maybe start building it with a placeholder icon and fill that in later.

**Comment by ann26** [comment]
ok thanks @carina1000

**Comment by cchristelis** [comment]
@ann26, the client asked for a few updates:
- Could we remove all the graphs etc from algae and invertebrates (while we don't have any data let's just add the icon, nothing more.
- For Fish at a site we have the total record count, hence we can populate the top number 
- We have string "native, non-native, translocated" [see: https://github.com/kartoza/healthyrivers/issues/168] so we can populate the bar graph.
- The diversity counts, we can keep with dummy data [, although if you have the time we could calculate it using: https://en.wikipedia.org/wiki/Diversity_index]
- Conservation status dummy pie chart, keep.
- Ecological condition pie chart remove.

**Comment by Vries14** [comment]
From @cchristelis comment:
- Graphs removed
- Top number populated for fish
- bar graph populated with "native" ,"Non- native"," translocated"
- dummies for conversation status and diversity counts kept.
- ecological pie chart removed
