### ISSUE TITLE
Match up Mockups and Website

### ISSUE THREAD

**Issue by carina1000** [kartoza/healthyrivers#153]
Change all Aquatic Invertebrates and Algae icons across the information system to match: 
https://drive.google.com/drive/folders/1fgljBJo-w47N-dnXZqqsIrcKcjVgKwoy?ogsrc=32 

## Landing Page:
 • Change top and bottom bar to match up with designs:

![Screen Shot 2018-08-20 at 10.01.41.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f36b7191a379ef0c2b50415b4fbe5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5cf14ee24f54a0123e66f43b.png)

• Change icons and add pie chart numbers if data is available
![Screen Shot 2018-08-20 at 09.54.58.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f36b7191a378e60c2e55415a46be5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb5cf14ee24f56a5123463f43b.png)

**Comment by cchristelis** [comment]
I think there is still an issue with the URLs and some of the logos at the footer.

**Comment by cchristelis** [comment]
Please make sure that the navigation bar also matches...

**Comment by ann26** [comment]
@cchristelis all links in the footer and navigation bar are matched.
but the bibliography page is not good (see below)
![Uploading screencapture-0-0-0-0-62302-bibliography-2018-09-26-11_40_53.png…]()

**Comment by cchristelis** [comment]
@carina1000 and @ann26, could you guys please figure out the layout of the Bibliography page.

**Comment by carina1000** [comment]
@dimasciput could you please upload some data into the staging/bibliography so that I can have a better understanding to design something. Thanks!

**Comment by carina1000** [comment]
@ann26 - PLEASE can you also remove that stripe after FBIS as discussed before (in both the top bar and footer.

**Comment by carina1000** [comment]
![Screen Shot 2018-10-16 at 13.06.43 copy.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a379ec0c2b57415b4dbc12071f0deee59b6be4e96625d91819e7c3680e71c53840aaba8a1cee08b8728b4f84e4bb831dc4ba6e37fb99cd1e604a5a45d0b50877b29359ca58fc4ae44e5ca21b3e6be272357d458653.png)
![Screen Shot 2018-10-16 at 13.06.47 copy.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a379ec0c2b57415b49bc12071f0deee59b6be4e96625d91819e7c3680e71c53840aaba8a1cee08b8728b4f84e4bb831dc4ba6e37fb99cd1e604a5a45d0b50877b29359c950fc4ae44e5ca21b3e6be37e367c4e8653.png)
