### ISSUE TITLE
Colours don't match up

### ISSUE THREAD

**Issue by carina1000** [kartoza/healthyrivers#156]
# Problem

Currently the Healthy Rivers staging site still has the LBIMS colours
![Screen Shot 2018-08-20 at 14.45.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f36b7191a379eb0c2f54415e47be5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb5cf14ce14e50a5173266f43b.png)

# Solution

Change the colours to be the same as designs: https://app.moqups.com/tim@kartoza.com/0RWHHxCONd/edit/page/a47486dd3
![Screen Shot 2018-08-20 at 15.19.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456f36b7191a379ea0c2a58415f46be5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c3caa984ecb5cf14ce04c53a411326bf43b.png)

**Comment by cchristelis** [comment]
This is also an issue on the side panel.
