### ISSUE TITLE
Biomes

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#159]
# Error

Biomes are not showing when selected

![Biomes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46ca9d952e8790ebc3abaf51ab57f5973d047d317c05f6782584b57ae7117a585d0d4eac400a584dadfddb78b4aa2e32db025fb28c341521842f1bbeba8315be04b924834a84b4be8c48c0e82f68.png)

**Comment by Vries14** [comment]
This happens in both healthyrivers and LEDET

**Comment by NyakudyaA** [comment]
I am going to close this. The layers all should be coming from the correct url. either staging or testing url which works. Please note that http://lbims.kartoza.com is no longer being maintained and all layers should not come from here. In fact it will be taken down soon.
cc @dimasciput
