### ISSUE TITLE
Download Data Missing columns

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#160]
# Problem

When I downloaded the CSV data, its missing certain fields:
- [x] latitude
- [x] longitude
- [x] location_site
- [x] taxon_class

# Proposed Solution 

Make sure these columns are showing.

**Comment by gubuntu** [comment]
same as https://github.com/kartoza/LEDET_BIMS/issues/200

**Comment by Vries14** [comment]
fields no longer missing
