### ISSUE TITLE
Admin boundaries they are too blinding!

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#165]
# Problem

When I search by admin boundaries, I get a blob of red, which is especially blinding when I'm working on a projecta.

# Proposed Solution

Increase the transparency and rather use one of the project's greens or olive greens in this feature than red.

**Comment by gubuntu** [comment]
that's a geoserver SLD styling task - @NyakudyaA ?

**Comment by cchristelis** [comment]
@gubuntu, @meomancer I think this is from the search result.

**Comment by cchristelis** [comment]
<img width="641" alt="screen shot 2018-08-22 at 3 01 53 pm" src="https://user-images.githubusercontent.com/2319504/44489256-497d8e00-a65b-11e8-9ffb-d54d33b4f3e8.png">

**Comment by Vries14** [comment]
Increased transparency with the green admin boundaries.

**Comment by gubuntu** [comment]
@Vries14 how did you do this? With the GeoServer SLD style?
