### ISSUE TITLE
It won't explode!

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#167]
# Problem

When I have completed my search in Swellendam I have a big 17 in the middle of the result AOI. It doesn't matter how far I zoom in it always remains a collection. I cannot get to the underlying site points.

# Proposed Solution

There must be a maximum zoom level beyond which no clustering is applied.

**Comment by gubuntu** [comment]
sounds like a duplicate of a LEDET issue. Zoom in reaaaaaaaallllly close and they'll explode. 

we need a better way to deal with this situation

**Comment by cchristelis** [comment]
@gubuntu, I've zoomed to the end, I think it is when taxa are clustered? which in itself is weird.
