### ISSUE TITLE
Geonode help screen section hyperlinks

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#176]
# Bug report

1.Upon opening your profile, click on the drop down arrow where your username is showing.
2.Click on help
3.Click on the "developer access" hyperlink at the sections area

# Error 

I get redirected  to a particular point in the  paragraphs and need to navigate to view above information. 

# Expected behaviour

When clicking on a hyperlink my expectation is to get directed to a heading to be able to view all info.

**Comment by Vries14** [comment]
See from the screencast,The hyperlinks goes to the wrong headings.![peek 2018-10-29 09-19](https://user-images.githubusercontent.com/42169058/47635208-e2012480-db5c-11e8-88f8-2eb889aa5a90.gif)

**Comment by dimasciput** [comment]
@Vries14 since user shouldn't be able to go to this page, I think this is fine
