### ISSUE TITLE
CSV upload

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#182]
# Problem

The CSV format and content has been updated.

# Proposed Solution

Add the new fields and upldoad the latest data.

**Comment by cchristelis** [comment]
[CFR Fish Data for FBIS.xlsx](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba461b7953d2fd0f723be1/125516c66e82c728ace21e0d46cbb2a863a48aba87a99b42b05cb092265467550b2d90693cc7f33ab0487e021b4d44be44095a47f9a88f29aeb56d79880e0bedd03f587d973943ffaa9e0dfd50e474d412dcfce9c85ecafa3f25ed8a8a4c391c02198dfe543ca39e5985.xlsx)

**Comment by dimasciput** [comment]
uploaded to staging, the formated csv : 
[fish_new.zip](https://github.com/kartoza/healthyrivers/files/2395685/fish_new.zip)

**Comment by cchristelis** [comment]
@dimasciput, there are some columns that have been added to the column, these need to be taken back to a model update. Perhaps @timlinux should also add input to how we should update the data model...

**Comment by dimasciput** [comment]
what columns that should be added to fish model ? everything ?

**Comment by cchristelis** [comment]
everything needs to be modeled out so perhaps @timlinux should give some input here.

**Comment by Vries14** [comment]
new fields matching example in comment from kartoza/django-bims#386,
