### ISSUE TITLE
Please change the logo

### ISSUE THREAD

**Issue by carina1000** [kartoza/healthyrivers#185]
Please change the logo at the top bar to following:
![Screen Shot 2018-09-19 at 09.18.09.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fa6b7191a378e60c2a59415f47be5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5ff54fe24e51ac133466f43b.png)

And the bottom bar:
![Screen Shot 2018-09-19 at 09.18.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a533a594304490012b9cfb6/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455fa6b7191a378e60c2a59415d4ebe5d4a1f06a3a3dc78e2a436628f0d0eeed43c5976ce3e40a5bad01fbf00e827821e81e4ef9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb5ff54fe24e53a1123e64f43b.png)

**Comment by ann26** [comment]
duplicate https://github.com/kartoza/healthyrivers/issues/194
