### ISSUE TITLE
Upcoming

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#188]
# Problem

Not all our features will be available for the next release. We would still like to show all mockuped features. 

# Proposed Solution

All features that will not be ready for version 1, should be greyed out with a hover text "Coming Soon"

**Comment by dimasciput** [comment]
Duplicate to https://github.com/kartoza/healthyrivers/issues/52

**Comment by Vries14** [comment]
@dimasciput  On the "detailed dashboard overview" the options to download graphs does not work...
Was this intended? Could we add the "coming soon" to these also?
