### ISSUE TITLE
Spatial filter with search for location site

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#207]
# Error

When searching for sites with spatial filter, all sites are showing and not just the sites within the spatial boundary

![Screenshot_2018-09-27 Healhtyrivers Map.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6952abafc89a0011b75b37/125516c66e82c728ace21e0d46db978826878dba87e6ab7cf60da1cc64167e3e7b53e3037584ef20ab5b6908190a0cef51250e04eee59b6be4e96625d91819e7c3680e25923c10aaea8419eb52bf218b4f84e4b9de1fc4eb3837fb99cd1e604a5a45d0b50877b29359c95ffc4ae44e5da4103767e777337e408653.png)

**Comment by dimasciput** [comment]
@Vries14 what is your steps?

**Comment by dimasciput** [comment]
you need to click apply filter

**Comment by Vries14** [comment]
1. Search "krom"
2. Click on the "western" boundary that was uploaded
3.Apply filter

Still yields the same results as to the screenshot.

**Comment by dimasciput** [comment]
@Vries14 can you try it again

**Comment by Vries14** [comment]
@dimasciput when I applied the spatial filter to sites like Eerste, swartkops, seekoei they were still not getting the expected results .

**Comment by dimasciput** [comment]
@Vries14 yes that's out of the custom boundary. 
![screen shot 2018-09-27 at 5 55 06 pm](https://user-images.githubusercontent.com/1979569/46141589-910cc080-c27e-11e8-9a78-67b779a5a1bb.png)

**Comment by Vries14** [comment]
So.... @dimasciput  When I do a search and apply custom boundary and none of the search results are within the boundary the results still shows outside the boundary? How can that be if im trying to see the results within my boundary ?

**Comment by dimasciput** [comment]
Ah sorry I just understand your question, let me take a look at it.

**Comment by dimasciput** [comment]
@Vries14 can you try again?

**Comment by Vries14** [comment]
This is now working @dimasciput , however it looks like the new changes to the "filters " caused some filters not to work with the spatial filter. eg when I apply the "non-native" filter with the spatial filter it seems not to work because it keeps on loading with no results.

**Comment by Vries14** [comment]
Fixed spatial filter with search for sites
