### ISSUE TITLE
Update search panel 

### ISSUE THREAD

**Issue by dimasciput** [kartoza/healthyrivers#216]
1. Swap STUDY REFERENCE and REFERENCE CATEGORY like mockup : 
![screen shot 2018-10-05 at 3 55 24 pm](https://user-images.githubusercontent.com/1979569/46525929-1b74a600-c8b7-11e8-83dd-e9cd24f6a691.png)

2. Move spatial filter to different panel
![screen shot 2018-10-05 at 3 56 20 pm](https://user-images.githubusercontent.com/1979569/46525999-3f37ec00-c8b7-11e8-8776-4f39785e0c2b.png)

3. Update origins filter like mockup : 
![image](https://user-images.githubusercontent.com/1979569/46526041-5e367e00-c8b7-11e8-88f4-c4d1b254ae76.png)

**Comment by dimasciput** [comment]
@NyakudyaA do we have ecoregion and catchment data ?

**Comment by cchristelis** [comment]
:+1:

**Comment by Vries14** [comment]
Search panel updated
