### ISSUE TITLE
error when trying to download CSV for sites

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#217]
# Bug report

1. Do a search on a site , eg : breede
2. Try to download CSV when results map.

# Error

I get a "data is empty" message

**Comment by Vries14** [comment]
@dimasciput The CSV is still not downloading

**Comment by dimasciput** [comment]
@Vries14 can you try again? it's working fine for me

**Comment by Vries14** [comment]
![site_search](https://user-images.githubusercontent.com/42169058/47139599-7e553c80-d2bc-11e8-9c1f-56fc4b1c4475.gif)

**Comment by Vries14** [comment]
CSV downloads when searching by site name
