### ISSUE TITLE
Detailed Dashboard Bug

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#219]
# Bug Report

@ann26 On the "detailed dashboard overview" the options to download graphs does not work...
Was this intended? Could we add the "coming soon" to these also?

**Comment by Vries14** [comment]
@ann26 None of the graphs are downloading under the "Fish" header in the detailed dashboard. (Only the pie charts are "coming soon", what about the bar graphs for records and origin)?

**Comment by anitanh** [comment]
hi @cchristelis and @Vries14 , the problem might be because of different screen size. I had this problem before where the image wasn't downloaded in the large screen but was fine in the smaller screen. I'll try to fix it.

**Comment by Vries14** [comment]
The graphs are downloading

**Comment by Vries14** [comment]
i tried again, and not downloading

**Comment by anitanh** [comment]
hi @Vries14 @dimasciput I'm not able to produce this on my machine. I am able to download all elements from the detailed dashboard in staging site, see below:

![peek 2018-10-31 14-46](https://user-images.githubusercontent.com/26101337/47773338-533b0600-dd1c-11e8-92a6-8f4ed998da23.gif)

![peek 2018-10-31 14-50](https://user-images.githubusercontent.com/26101337/47773341-53d39c80-dd1c-11e8-81e1-65512e695082.gif)

**Comment by Vries14** [comment]
@ann26 , I realised that it is not downloading in Firefox

**Comment by anitanh** [comment]
thanks for the clue @Vries14 , I fixed it in #287
