### ISSUE TITLE
Site search not yielding results

### ISSUE THREAD

**Issue by Vries14** [kartoza/healthyrivers#222]
# Bug report

When I search for a particular site I either get no results or I do get results, but different to the search

eg : search for Eerste , I got 196 sites but none listed Eerste.
search for Dwars, I got no results

# Expected behaviour

Results should match the search

**Comment by dimasciput** [comment]
@Vries14 if there is no exact name found it will search using fuzzy search, so you can see at the title it will displays 'similar to...'. . Probably Dwars is not close to any records, I'm going to check it later

**Comment by Vries14** [comment]
As you can see from the screenshot the exact name is "Eerste"
![screenshot_2018-10-12 healhtyrivers map](https://user-images.githubusercontent.com/42169058/46852483-72203980-cdfb-11e8-8fea-4057e127267c.png)

When I search for it, I cant seem to find it (Note: this happens with other sites also , just try to search for another site like "berg")
![screenshot_2018-10-12 healhtyrivers map 1](https://user-images.githubusercontent.com/42169058/46852514-90863500-cdfb-11e8-9825-c4277d7f811e.png)

**Comment by dimasciput** [comment]
ah ok, working on it, thanks

**Comment by Vries14** [comment]
Working nicely now
