### ISSUE TITLE
Implement UI for updating layer order for Non biodiversity layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#227]
# Problem

Please put the layers in the following order when the map is started up: Biodiversity, Rivers 500K, Water Management Areas, Primary Catchment, Secondary Catchment, Tertiary Catchment, Quaternary catchment (?), Quinary catchment , Ecoregion Level 1, Critical Biodiversity Areas, Protected Areas, Fish Sanctuaries, Administrative boundaries. 

# Solution

Currently adding non biodiversity layers will automatically add all the layers into the bottom of the layer list. If we have a fixed order we could add them in that order but once someone wants to change the order again it becomes difficult to manage.

* Implement UI like this
![screenshot 2018-10-12 at 12 18 21](https://user-images.githubusercontent.com/2510900/46863899-f634ea00-ce18-11e8-8b17-dfeec602a5fa.png)

**Comment by gubuntu** [comment]
Where will this be managed?

How does it interact with user's own ordering (if they re-order the layers)?

What happens if any of those layers are not available?

What happens with other layers that are available? (I'm thinking how this will affect LEDET)

**Comment by dimasciput** [comment]
@gubuntu 

> Where will this be managed?

In the non biodiversity layer admin page

> How does it interact with user's own ordering (if they re-order the layers)?

If someone changing order in the admin page, it will reset user's own ordering

**Comment by Vries14** [comment]
Layers rearranged into the right order. Admin able to change order and reset users own ordering.
