### ISSUE TITLE
Add missing layers for non biodiversity layers

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#229]
#Problem

The following layers are missing: Quaternary catchments, Land use, NFEPAs and geomorphological zones. Please add or enquire where to find these.

# Solution
Please add these

**Comment by NyakudyaA** [comment]
Added these layers to the backend and front end
![screenshot 2018-10-12 at 15 29 42](https://user-images.githubusercontent.com/2510900/46872174-b7f8f400-ce33-11e8-92c3-8acf37c05e6d.png)
![screenshot 2018-10-12 at 15 30 00](https://user-images.githubusercontent.com/2510900/46872175-b8918a80-ce33-11e8-8e54-0453d70d3df0.png)

**Comment by gubuntu** [comment]
oh so heaalthyrivers is using django admin to configure layers while ledet fetches layers from local GeoNode. Can both sites use both methods as required?
