### ISSUE TITLE
fix layer order for non biodiversity layers at the bottom of the list

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#231]
# Problem

We see there is a NFEPAs layer, however it is labelled strangely. Please change.

**Comment by NyakudyaA** [comment]
It is fixed and the layer name has been changed

**Comment by gubuntu** [comment]
are you making the same fixes on LEDET (the danger of having multiple copies...)

**Comment by NyakudyaA** [comment]
@gubuntu this is just a friendly layer name. There is not duplication happening because the resource is just fetching wms with layer name and I am just applying a title which is already visible in GeoServer
