### ISSUE TITLE
Fix legend position and behaviour

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#233]
# Problem

One can't escape or close the legend easily as it covers the context layer panel. Please ensure this is possible. Alternatively, reposition where the legend opens so that it doesn't restrict the user from unticking the layer. Maybe there could be a hover option for the legend?

# Solution

* investigate change for legend placement
* Fix interaction of legend - allow a user to easily close the legend

**Comment by gubuntu** [comment]
duplicate of https://github.com/kartoza/django-bims/issues/380 and preceding issues

**Comment by NyakudyaA** [comment]
will close this one and refer this to the original ticket you created
