### ISSUE TITLE
Base-map naming conventions and list

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#234]
# Problem

What are the green features on the base map? Please specify what Klokantech terrain is? Perhaps we only need the South Africa 1:50k Toposheet, NGI OSM aerial photographs and the Bing layer (This is nice, but specify what Bing is).

# Solution

Please make it happy

**Comment by NyakudyaA** [comment]
TODO: Tim come up with a nicer scheme for labelling the base layers and share with Helen and Toni. Dimas to update the map accordingly. We will keep the current set of base layers.

**Comment by NyakudyaA** [comment]
@timlinux any comment on this one. Still waiting for your input

**Comment by gubuntu** [comment]
Use these names and this order:

- Klokantech Terrain -> Terrain (default on)
- 1:50k toposheets -> Topography
- OpenStreetMap
- Aerial photography
- Bing Satellite Hybrid 
- Plain B&W
- Plain greyscale

On Limpopo BIMS, the attribution (which I had fixed) is all wrong again. The attribution is where the full name and publisher must go for each base map. Apply these to LEDET as well

**Comment by timlinux** [comment]
@NyakudyaA please go with the scheme proposed by Gavin for FBIMS

**Comment by Vries14** [comment]
Base map naming changed
