### ISSUE TITLE
UI improvements for sites and records

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#239]
# Problem

The circles under each module should state the number of sites and number of records, i.e. not just records.

Number of sites + number of species - occurrences we will add later when we do v2. See mockup from Jeremy. Gray out crabs and algae and hide thei numbers for now.

**Comment by dimasciput** [comment]
@timlinux where is the mockup? Couldn't find it from dropbox

**Comment by ann26** [comment]
hi @dimasciput I found it in the email, although I am not sure if this is the updated one.
![screenshot from 2018-10-15 16-33-23](https://user-images.githubusercontent.com/26101337/46949864-095fe800-d0ad-11e8-8753-57523e6a84eb.png)
