### ISSUE TITLE
Fix inconsistencies in reporting

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#247]
# Problem

Please show number of records  as well as number of sites when searching for a particular river.

![screenshot 2018-10-12 at 16 49 56](https://user-images.githubusercontent.com/2510900/46876600-095ab080-ce3f-11e8-9d36-ec979a108bac.png)

See screenshot below. Also inconsistency in counts between search and site display.

**Comment by Vries14** [comment]
There are still inconsistency between counts and sites when applying the other filters
![image](https://user-images.githubusercontent.com/42169058/47083184-26f99280-d210-11e8-870d-8bd5b2ebf5e5.png)

**Comment by dimasciput** [comment]
@Vries14 what is your filter? Because I couldn't reproduce it

**Comment by Vries14** [comment]
@dimasciput please reproduce the following steps:

1.Add the collector filter on "Barnard, K.H., Thorne, C.W. and Harrison A.C."
2. Open sites and click on "Olifants"

**Comment by dimasciput** [comment]
@Vries14 please try again

**Comment by Vries14** [comment]
Inconsistencies in reporting fixed
