### ISSUE TITLE
Add spatial coordinates in download

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#248]
# Problem

Please add spatial coordinates in the CSV when downloading site information from the detailed dashboard.

**Comment by gubuntu** [comment]
see also https://github.com/kartoza/LEDET_BIMS/issues/200

**Comment by dimasciput** [comment]
@gubuntu this is for detail dashboard

**Comment by Vries14** [comment]
The coordinates get swapped when downloading the CSV. Please ensure that it is in the right way : lat-long

**Comment by Vries14** [comment]
Coordinates added when downloading CSV from detailed dashboard.
