### ISSUE TITLE
Fix species search

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/healthyrivers#250]
# Problem

This should be more detailed (use the IUCN website and Jeremy's mockup (below) as an example). Include Taxonomy, conservation status and endemism on this panel.

![screenshot 2018-10-12 at 16 58 30](https://user-images.githubusercontent.com/2510900/46877044-1fb53c00-ce40-11e8-9539-b891b6d67cd3.png)

# Solution

Lets start by extending our current view to show the additional fields of conservation status, origin and endemism.

**Comment by dimasciput** [comment]
Already added this to staging

**Comment by Vries14** [comment]
Conservation status already present( at the top ). Origins and endemism fields added.
