### ISSUE TITLE
FR 30: The FBIS shall allow users to filter results based on appropriate filters and search terms on the UI.

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#52]

**Comment by cchristelis** [comment]
In our previous planning session we re-worked the filters:
- Module Selection Section: This needs to be greyed out with a hover over "Coming Soon"
- Temporal Scale: Rename from date
- Spatial Scale: We will move this into its own function see: #138
- Origins: Update naming to match the latest category.
- Ecological Condition: Add, but greyed out with "Coming Soon" on hover.
- Conservation Status: Add, greyed out with "Coming Soon" on hover.
- Study Reference: Update this from using the collector to rather using the study reference.
- Reference Category: Add, based on the categories we have available in the system. (See updated CSV.)

![Screen Shot 2018-09-23 at 11.01.24 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/53ba461b7953d2fd0f723be1/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6456f06b7191a379ee0c2b50415d4abc21254d58eeb9cb74fce36f34985619e8803c0b75c73b43aabed64cba00ba208a1d80e2ef8e4fc5fa2137a5dad11b61435c52dcbd4f3fb2984cc259f348e64a56a2163564e775376e0a.png)

**Comment by Vries14** [comment]
Changes to filters added
