### ISSUE TITLE
Set up project

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#55]
# Problem 

We need to set up the code base for this project.

# Proposed Solution

Use cookie cutter (https://github.com/audreyr/cookiecutter) or similar and develop a template that we can use for future projects.

**Comment by cchristelis** [comment]
We decided to not go with template. Let's use projecta. Django 2<=  (Moving to 2.2). Python 3.5 <= .

**Comment by dimasciput** [comment]
Added in https://github.com/kartoza/healthyrivers/pull/72
