### ISSUE TITLE
Database schema migration

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#60]
# Problem 

The old database was over normalized, which lead to complexity in both uploading and managing the data. Secondly it lead to many unused features and a lot of missing data.

# Proposed Solution 

Do a schema migration according to the plan set out in this document: https://docs.google.com/document/d/18xQvIipQO4IyeV2Ik6uBtagsY-0SADlSWpNZyjkqwj0/edit?usp=sharing

**Comment by cchristelis** [comment]
@sonlinux, please indicate to myself and @timlinux when you are done with this. As this is required for us to start on #69

**Comment by sonlinux** [comment]
@cchristelis and @timlinux  
I have  worked on this ticket and it is done. 
We can start on #69 
Thanks.
