### ISSUE TITLE
High fidelity mockups - map view

### ISSUE THREAD

**Issue by cchristelis** [kartoza/healthyrivers#66]
# Problem 

We need High fidelity designs for
- https://xd.adobe.com/view/1f8f3aa7-aa2f-4c1c-9bab-fcfae1f4ca40/screen/1a6f28c3-5004-44b1-accd-654a88331e78/map
- https://xd.adobe.com/view/1f8f3aa7-aa2f-4c1c-9bab-fcfae1f4ca40/screen/c6530721-7d9e-4bbb-b01e-3782c28ff6b7/Liesbeek-River
- https://xd.adobe.com/view/1f8f3aa7-aa2f-4c1c-9bab-fcfae1f4ca40/screen/9872b32e-3348-4f2a-877e-e498403d074b/map-my-site-upload

# Proposed Solution

Develop these and export them as HTML and CSS.

**Comment by dimasciput** [comment]
Hi @carina1000 , do you have any progress for this?

**Comment by carina1000** [comment]
@dimasciput I will have for you by tomorrow
