### ISSUE TITLE
We need an awesome landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/healthyrivers#75]
![screen shot 2018-02-15 at 14 32 10](https://user-images.githubusercontent.com/178003/36256821-3b6512b2-125d-11e8-8726-da143f0cf1fa.png)

The landing page should:

* be beautiful
* should include a strapline that clearly conveys the intent and purpose of the web site
* should set the scene for the experience (design, navigation etc.) that the user will experience when moving through the site
* should include
 * partner logos
 * kartoza logo
 * a link back to this git repository ('get the code!')
 * a link back to this issue tracker so that it is easy for people to report issues they might encounter.

**Comment by timlinux** [comment]
@carina1000 and @dimasciput can you have this done for next wed please

**Comment by dimasciput** [comment]
@carina1000 do you have the mockups ready?

**Comment by carina1000** [comment]
@dimasciput please see the Mock-ups so far: https://app.moqups.com/carina@kartoza.com/tROrxQWBGE/edit/page/a6d27d3cc

@timlinux doesn't creating the main landing page rely a lot on the feedback of the client? They said they would get back to me on colours and biodiversity icons. Should we not wait for that?

**Comment by dimasciput** [comment]
@carina1000 do we need to update the current landing page?

**Comment by carina1000** [comment]
@dimasciput please update the HR according to my mockups:https://app.moqups.com/tim@kartoza.com/0RWHHxCONd/edit/page/a98a4f9db 
*note they changed the icons again a bit so please it's important they are updated, you can find them here: https://drive.google.com/drive/folders/1fgljBJo-w47N-dnXZqqsIrcKcjVgKwoy

![screen shot 2018-08-08 at 08 00 33](https://user-images.githubusercontent.com/35214829/43818941-3f1bd802-9ae1-11e8-8ff4-b8bb6a7421e6.png)
![screen shot 2018-08-08 at 08 00 41](https://user-images.githubusercontent.com/35214829/43818942-3f3c9d08-9ae1-11e8-9324-632da4b38b71.png)
![screen shot 2018-08-08 at 08 00 46](https://user-images.githubusercontent.com/35214829/43818943-3f5720ec-9ae1-11e8-93c6-c5bbb22b2dc3.png)

**Comment by cchristelis** [comment]
@carina1000, please ensure that these icons are also updated on the side-panel. Check in with @ann26 at kartoza/healthyrivers/issues/150.

**Comment by dimasciput** [comment]
@carina1000 updated http://staging.healthyrivers.kartoza.com

**Comment by Vries14** [comment]
landing page updated based on comments on _8 aug_ and _20 aug_
