### ISSUE TITLE
Make schema migration script work cleanly on non fresh restore database.

### ISSUE THREAD

**Issue by sonlinux** [kartoza/healthyrivers#77]
## Problem

The current script only works against a fresh restore of the database 
it errors if run against a restore with already some changes in it.

## Solution

Make the script flexible enought to be able to run again a database with already changes made to it,
For example
```
DROP TABLE "table_name";
```
will exist the script from running further if "table_name" has already been deleted or its name modified.

**Comment by gubuntu** [comment]
you can use `IF EXISTS`

**Comment by sonlinux** [comment]
Yes @gubuntu thats an option am going with.
Thanks

**Comment by cchristelis** [comment]
@sonlinux, this is a once off activity. Please don't add unneeded complexity.

**Comment by sonlinux** [comment]
Okay @cchristelis 
I thought it would be needed just for the sake of clarifiying the database structure at some point.

**Comment by cchristelis** [comment]
This script creates a new baseline. If we need further scripted changes we'll follow them up in a separate ticket and a separate script. 
But very soon we'll move over to having these tables managed from django models.
So at the point where we need to assert reversibility or sequencing, the migrations will already be managed by django migrations.
