### ISSUE TITLE
We need an IUCN API key

### ISSUE THREAD

**Issue by timlinux** [kartoza/healthyrivers#78]
I have made an application here:

http://apiv3.iucnredlist.org/api/v3/token

We will use the key to (e.g. nightly) resolve which species listed in our database are red databook species.

Note there are interesting capabilities with the IUCN API for mapping:

http://apiv3.iucnredlist.org/spatial

Note there are OGC web services available too...

And for looking up species status:

http://apiv3.iucnredlist.org/api/v3/species/<species-name>?token=<token-id>

Assuming we have a correct name it will resolve to a JSON document like this;

http://apiv3.iucnredlist.org/api/v3/species/loxodonta%20africana?token=9bb4facb6d23f48efbf424bb05c0c1ef1cf6f468393bc745d42179ac4aca5fee

**Comment by timlinux** [comment]
I have applied for the key, waiting for approval

**Comment by dimasciput** [comment]
@timlinux did you get the key? can you email me the key?
