### ISSUE TITLE
Implement base model for fish

### ISSUE THREAD

**Issue by timlinux** [kartoza/healthyrivers#92]
Dimas can you please implement these models for fish:

![screen shot 2018-02-23 at 14 32 39](https://user-images.githubusercontent.com/178003/36594631-9a797702-18a7-11e8-9542-88277c3cbdcd.png)

- [ ] include CRUD tests for each model
- [ ] add admin managers for them
- [ ] make a form that will allow us to upload records as a CSV file and have them imported into the fish and site models.

We need to have this implemented by next Wed please.

**Comment by cchristelis** [comment]
could we follow these up in individual tickets? Also please move this to ready or in progress as applicable.
