### ISSUE TITLE
We need to integrate pygbif

### ISSUE THREAD

**Issue by timlinux** [kartoza/healthyrivers#93]
See #92 - when an insert is made for a fish record, we should check if there is a matching taxon for that species name in the taxon table. If there is not we need to do a name search using pygbif to fetch the authoriative name and GBIF taxon id. This should be written into the taxon table, and the taxon id should be updated in the fish table.

https://github.com/sckott/pygbif

Please set up a zoom call with me if you need more context. We need this done for next Wed.

**Comment by cchristelis** [comment]
@timlinux, are you happy with how this has been implemented.
